### ISSUE TITLE
TorchStudio not installing: Error while installing packages

### ISSUE THREAD

**Issue by pypdeveloper** [TorchStudio/torchstudio#53]
When attempting to install torchstudio I am getting the error:

`# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/homebrew/Caskroom/miniconda/base/envs/TorchStudio/lib/python3.11/site-packages/conda/exception_handler.py", line 16, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Caskroom/miniconda/base/envs/TorchStudio/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 126, in do_call
        return getattr(module, func_name)(args, parser)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Caskroom/miniconda/base/envs/TorchStudio/lib/python3.11/site-packages/conda/notices/core.py", line 123, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Caskroom/miniconda/base/envs/TorchStudio/lib/python3.11/site-packages/conda/cli/main_install.py", line 22, in execute
        install(args, parser, "install")
      File "/opt/homebrew/Caskroom/miniconda/base/envs/TorchStudio/lib/python3.11/site-packages/conda/cli/install.py", line 387, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "/opt/homebrew/Caskroom/miniconda/base/envs/TorchStudio/lib/python3.11/site-packages/conda/cli/install.py", line 414, in handle_txn
        unlink_link_transaction.download_and_extract()
      File "/opt/homebrew/Caskroom/miniconda/base/envs/TorchStudio/lib/python3.11/site-packages/conda/core/link.py", line 258, in download_and_extract
        self._pfe.execute()
      File "/opt/homebrew/Caskroom/miniconda/base/envs/TorchStudio/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 792, in execute
        progress_bar = self._progress_bar(prec_or_spec, leave=False)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Caskroom/miniconda/base/envs/TorchStudio/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 869, in _progress_bar
        progress_bar = ProgressBar(
                       ^^^^^^^^^^^^
      File "/opt/homebrew/Caskroom/miniconda/base/envs/TorchStudio/lib/python3.11/site-packages/conda/common/io.py", line 477, in __init__
        self.pbar = self._tqdm(
                    ^^^^^^^^^^^
      File "/opt/homebrew/Caskroom/miniconda/base/envs/TorchStudio/lib/python3.11/site-packages/conda/common/io.py", line 533, in _tqdm
        return tqdm(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Caskroom/miniconda/base/envs/TorchStudio/lib/python3.11/site-packages/tqdm/asyncio.py", line 24, in __init__
        super(tqdm_asyncio, self).__init__(iterable, *args, **kwargs)
    TypeError: init_patch() takes 1 positional argument but 2 were given

`$ python_api install pytorch torchvision torchaudio torchtext -c pytorch`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/opt/homebrew/Caskroom/miniconda/base/envs/TorchStudio
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/usr/bin:/bin:/usr/sbin:/sbin;/opt/homebrew/Caskroom/miniconda/base/en
                          vs/TorchStudio/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /Users/ayushdeolasee/.condarc
 populated config files : /Users/ayushdeolasee/.condarc
          conda version : 23.5.2
    conda-build version : not installed
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=arm64
                          __osx=14.0=0
                          __unix=0=0
       base environment : /opt/homebrew/Caskroom/miniconda/base/envs/TorchStudio  (writable)
      conda av data dir : /opt/homebrew/Caskroom/miniconda/base/envs/TorchStudio/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/pytorch/osx-arm64
                          https://conda.anaconda.org/pytorch/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/homebrew/Caskroom/miniconda/base/envs/TorchStudio/pkgs
                          /Users/ayushdeolasee/.conda/pkgs
       envs directories : /opt/homebrew/Caskroom/miniconda/base/envs/TorchStudio/envs
                          /Users/ayushdeolasee/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.5.2 requests/2.29.0 CPython/3.11.4 Darwin/23.0.0 OSX/14.0
                UID:GID : 501:20
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

Upload successful.
Exception ignored in: <function tqdm.__del__ at 0x1013ddda0>
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/TorchStudio/lib/python3.11/site-packages/tqdm/std.py", line 1145, in __del__
    self.close()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/TorchStudio/lib/python3.11/site-packages/tqdm/std.py", line 1264, in close
    if self.disable:
       ^^^^^^^^^^^^
AttributeError: 'tqdm_asyncio' object has no attribute 'disable'

Error while installing packages`

I am getting this error on a M1 Max MacBook Pro, as well as the latest Ubuntu package running on an intel processor. I am getting the same error on both the machines, even after multiple attempts. I tried installing on python 3.11 and 3.10, the error still persist.

**Comment by drjkpalli** [comment]
yep, same here

**Comment by divideconcept** [comment]
I can repro the issue. Looks like PyTorch recently switched from conda to pip as their recommended install method: https://github.com/pytorch/pytorch.github.io/commit/763011d380f7c2acb265e7d9cbd7836436267204
The next update of TorchStudio will therefore switch to this procedure as well, which hopefully will be more stable than the conda procedure which had a few breaks and issues over the years...

**Comment by divideconcept** [comment]
Issue solved with 0.9.16: https://github.com/TorchStudio/torchstudio/releases/tag/0.9.16
Make sure to delete ~/TorchStudio before running 0.9.16
