### ISSUE TITLE
Error during installation with CUDA "failed to parse CPython sys.version: '3.12.1"

### ISSUE THREAD

**Issue by zaliir** [TorchStudio/torchstudio#62]
Error during installation with CUDA 

![error install torchstudio with CUDA](https://github.com/TorchStudio/torchstudio/assets/65438199/0dacd527-0518-499f-a5a9-f3408448078e)

**message error:**
Checking the latest supported CUDA version...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/dev/TorchStudio/torchstudio/pythoninstall.py", line 33, in <module>
    import requests
  File "/home/ai/TorchStudio/python/lib/python3.12/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/ai/TorchStudio/python/lib/python3.12/site-packages/urllib3/__init__.py", line 14, in <module>
    from ._base_connection import _TYPE_BODY
  File "/home/ai/TorchStudio/python/lib/python3.12/site-packages/urllib3/_base_connection.py", line 5, in <module>
    from .util.connection import _TYPE_SOCKET_OPTIONS
  File "/home/ai/TorchStudio/python/lib/python3.12/site-packages/urllib3/util/__init__.py", line 5, in <module>
    from .request import SKIP_HEADER, SKIPPABLE_HEADERS, make_headers
  File "/home/ai/TorchStudio/python/lib/python3.12/site-packages/urllib3/util/request.py", line 32, in <module>
    import zstandard as _unused_module_zstd  # type: ignore[import] # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/TorchStudio/python/lib/python3.12/site-packages/zstandard/__init__.py", line 38, in <module>
    if platform.python_implementation() in ("CPython",):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/TorchStudio/python/lib/python3.12/platform.py", line 1153, in python_implementation
    return _sys_version()[0]
           ^^^^^^^^^^^^^^
  File "/home/ai/TorchStudio/python/lib/python3.12/platform.py", line 1113, in _sys_version
    raise ValueError(
**ValueError: failed to parse CPython sys.version: '3.12.1 | packaged by Anaconda, Inc. | (main, Jan 19 2024, 15:51:05) [GCC 11.2.0]'**

Error while installing packages

**Comment by radsulcorp** [comment]
This is the same issue as issue #60

**Comment by divideconcept** [comment]
@zaliir @radsulcorp this should now be fixed in 0.9.17: https://github.com/TorchStudio/torchstudio/releases/tag/0.9.17
